"""rename address

Revision ID: 469493978cea
Revises: 04ed7a24facf
Create Date: 2023-11-16 09:13:27.509948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469493978cea'
down_revision = '04ed7a24facf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###